export const ISIS_CASE_STUDY =   {
    "title": "ISIS Organic",
    "subtitle": "The E-commerce Transformation Story of iSiSOrganic",
    "intro": "Every FMCG brand has a story, and for iSiSOrganic, that story is one of transformation, resilience, and strategic execution. As a leading Egyptian brand in the organic and natural products sector with over 40 years in the market, iSiSOrganic has built a reputation for delivering high-quality honey, herbal teas, water, oils, snacks, and juices to health-conscious consumers. However, despite its strong presence in physical retail stores, iSiSOrganic was struggling to establish a stronghold in the e-commerce space.",
    "amazon": {
      "title": "AboutAmazon Ads",
      "paragraphs": []
    },
    "expansion": {
      "title": "Digital Presence",
      "paragraphs": []
    },
    "metrics": [
      {
        "value": 245,
        "suffix": "%",
        "label": "E-commerce growth"
      },
      {
        "value": 2740,
        "suffix": "%",
        "label": "YOY Amazon sales"
      }
    ],
    "blogLine": "245% growth in e commerce, 2,740% YOY growth in Amazon Sales",
    "sections": [
      {
        "heading": null,
        "paragraphs": [
          "The E-commerce Transformation Story of iSiSOrganic",
          "The e commerce TransformationStory of iSiSOrganic",
          "The Foundation on Amazon",
          "Digital Presence: Taking Over the Entire E-commerce Arm",
          "Growth Strategy: Scaling iSiSOrganic’s E-commerce Growth",
          "1. The Audit Phase: Understanding Platform Performance",
          "2. Strengthening iSiSOrganic’s Presence Across Platforms",
          "3. The Promotions Strategy: Selling at the Right Time",
          "4. Preparing for Growth: Avoiding Stockouts & Maximizing Fulfillment Rate.",
          "4. Preparing for Growth: Avoiding Stockouts & Maximizing Fulfillment Rate.Scaling fast can be a double edged sword. If you don’t plan ahead, you end up with stockshortages, fulfillment failures, and lost sales opportunities.That’s why we worked closely with iSiSOrganic to forecast product demand, adjust production timelines, and optimize fulfillment.",
          "5. Setting Clear KPIs for EOY Growth",
          "5. Setting Clear KPIs for EOY Growth With the strategy locked in, we built a clear forecast for the months ahead, tracking spending, sales growth, and advertising efficiency.",
          "1. The Audit Phase: Understanding Platform Performance"
        ]
      },
      {
        "heading": "AboutAmazon Ads",
        "paragraphs": []
      },
      {
        "heading": "ISIS OrganicCase Study",
        "paragraphs": []
      },
      {
        "heading": "SekemCase StudyComing soon",
        "paragraphs": []
      },
      {
        "heading": "RehanaCase Study",
        "paragraphs": []
      },
      {
        "heading": "SpritzCase Study",
        "paragraphs": [
          "Scaling FMCG on E- commerce:",
          "iSiSOrganic 2,700% YOY Growth Story",
          "Scaling FMCG on E- commerce:",
          "iSiSOrganic 2,700% YOY Growth Story",
          "Every FMCG brand has a story, and for iSiSOrganic, that story is one of transformation, resilience, and strategic execution. As a leading Egyptian brand in the organic and natural products sector with over 40 years in the market, iSiSOrganic has built a reputation for delivering high-quality honey, herbal teas, water, oils, snacks, and juices to health-conscious consumers. However, despite its strong presence in physical retail stores, iSiSOrganic was struggling to establish a stronghold in the e-commerce space.",
          "Every FMCG brand has a story, and for iSiSOrganic, that story is one of transformation, resilience, and strategic execution. As a leading Egyptian brand in the organic and natural products sector from more than 40 years in market, iSiSOrganic has built a reputation for delivering high quality honey, herbal teas, water, oils, snacks, and juices to health conscious consumers. However, despite its strong presence in retail stores, iSiSOrganic was struggling to establish a stronghold in the e-commerce exist.",
          "The Ecommerce Transformation Story of iSiSOrganic",
          "Every FMCG brand has a story, and for iSiS Organic, that story is one of transformation, resilience, and strategic execution. As a leading Egyptian brand in the organic and natural products sector from more than 40 years in market, iSiSOrganic has built a reputation for delivering high quality honey, herbal teas, water, oils, snacks,and juices to health conscious consumers. However, despite its strong presence in retailstores, iSiSOrganic was struggling to establish a stronghold in the ecommerce exist.",
          "In April 2024, iSiSOrganic partnered with dblshot to manage its Amazon presence, kicking off a major digital transformation. Initially, the brand faced several roadblocks: unoptimized listings, a fragmented online catalog, zero advertising efforts, and weak, inconsistent PO fulfillment rates that hurt overall sales.",
          "dblshot executed a focused turnaround strategy. By completely revamping iSiSOrganic's Amazon catalog, optimizing product listings, and launching high-impact ad campaigns, visibility and sales surged. The results were immediate, delivering stronger conversions, flawless fulfillment, and a skyrocketing 900% growth on Amazon in just 4 months.",
          "In April 2024, iSiSOrganic partnered with Doubleshot to manage its presence on Amazon, marking the beginning of its digital transformation journey. At the time, iSiSOrganic faced several critical challenges:",
          "∙Unoptimized product listings that hindered visibility and conversions.",
          "∙A limited catalog presence, with only a fraction of its products available online.",
          "∙Zero advertising efforts, making it nearly invisible in search results.",
          "∙Weak sales performance, with inconsistent purchase order (PO) fulfillment rates.",
          "With a focused strategy, Doubleshot began by revamping iSiSOrganic Amazon catalog, optimizing listings, and launching high impact advertising campaigns to improve visibility and drive sales. The results were immediate, a significant uptick in conversions and better fulfillment execution.",
          "Refer to iSiSOrganic case study to discover the behind the scenes of a skyrocketing 900% growth on amazon in just 4 months",
          "In April 2024, iSiSOrganic partnered with Doubleshot to manage its presence on Amazon, marking the beginning of its digital transformation journey. At the time, iSiSOrganic faced several critical challenges:",
          "∙A limited catalog presence, with only a fraction of its products available online.",
          "∙Zero advertising efforts, making it nearly invisible in search results.",
          "∙Weak sales performance, with inconsistent purchase order (PO) fulfillment rates.",
          "With a focused strategy,Doubleshot began by revamping iSiSOrganic Amazon catalog, optimizing listings, and launching high impact advertising campaigns to improve visibility and drive sales. The results were immediate, a significant uptick in conversions and better fulfillment execution.Refer to iSiSOrganic case study to discover the behind the scenes of a skyrocketing 900% growth on amazon just in 4 months.",
          "After witnessing exponential growth on Amazon, iSiSOrganic made a bold move in August 2024, expanding its partnership with dblshot to take over its entire digital arm. This meant managing not only Amazon but also Noon, Breadfast, and Goodsmart, as well as spearheading new brand launches on Botit, Rabbit, and Talabat.",
          "Enhance and optimize the entire catalog across all major e-commerce platforms.",
          "Maximize sales while achieving the most efficient cost-to-advertising ratio.",
          "Scale operations to their full potential by leveraging promotions, visibility strategies, and data-driven optimizations.",
          "By late 2024, iSiSOrganic had evolved from a brand with a weak online footprint into a dominant force in the e-commerce space. This case study takes you behind the scenes of that transformation—revealing how a data-driven, strategic approach turned iSiSOrganic into one of the fastest-growing FMCG brands online.",
          "After witnessing exponential growth on Amazon, iSiSOrganic made a bold move in August 2024, expanding its partnership with Doubleshot to take over its entire digital arm. This meant managing not only Amazon but also Noon, Breadfast, GoodsMart, and new launches on Botit, Rabbit, and Talabat.",
          "The goal was clear:",
          "Enhance and optimize the entire catalog across all major e-commerce platforms.",
          "Maximize sales while achieving the best cost-to-advertising ratio.",
          "Scale operations to their full potential by leveraging promotions, visibility strategies, and data-driven optimizations.",
          "By late 2024, iSiSOrganic had evolved from a brand with a weak online presence to a dominant force in the E-commerce space. This case study takes you behind the scenes of that transformation—how a data-driven, strategic approach turned iSiSOrganic into one of the fastest-growing FMCG brands online.",
          "Digital Presence: Taking Over the Entire E-commerce Arm",
          "After witnessing exponential growth on Amazon, iSiSOrganic made a bold move in August 2024, expanding partnership with Doubleshot to take over its entire digital arm. This meant managing not only Amazon but also Noon, Breadfast, Goodsmart, and new launches on Botit, Rabbit, and Talabat.The goal was clear: ∙Enhance and optimize the entire catalog across all major e-commerce platforms. Maximize sales while achieving the best cost-to-advertising ratio. Scale operations to their full potential by leveraging promotions, visibility sttegies, and datadriven optimizations. By late 2024, iSiSOrganic had evolved from a brand with a weak online presence to a dominant force in the Ecommerce space. This case study takes you behind the scenes of that transformation, how a datadriven, strategic approach turned iSiSOrganic into one of the fastest growing FMCG brands online.",
          "Success in e-commerce doesn’t happen by accident—it’s built on strategy, planning, and execution. After our breakthrough results on Amazon, we knew that iSiSOrganic had the potential to dominate across all major e-commerce platforms. But expansion isn’t just about listing more products or running more ads; it requires a structured, data-driven approach to maximize sales while keeping operations seamless. That’s why we mapped out a detailed strategy for the upcoming quarters, ensuring that iSiSOrganic wasn’t just keeping up, but staying ahead of the competition.",
          "Success in e-commerce doesn’t happen by accident, it’s built on strategy, planning, and",
          "execution. After our breakthrough results on Amazon, we knew that iSiSOrganic had the",
          "potential to dominate across all major e-commerce platforms. But expansion isn’t just about",
          "listing more products or running more ads; it requires a structured, data-driven approach to",
          "maximize sales while keeping operations seamless. That’s why we mapped out a detailed",
          "strategy for the upcoming quarters, ensuring that iSiSOrganic wasn’t just keeping up but staying",
          "ahead of the competition.",
          "Success in e-commerce doesn’t happen by accident, it’s built on strategy, planning, and",
          "execution. After our breakthrough results on Amazon, we knew that iSiSOrganic had the",
          "listing more products or running more ads; it requires a structured, data-driven approach to",
          "maximize sales while keeping operations seamless. That’s why we mapped out a detailed",
          "strategy for the upcoming quarters, ensuring that iSiSOrganic wasn’t just keeping up but stayig ahead of the competition.",
          "Before scaling iSiSOrganic’s presence across Noon, Breadfast, and Goodsmart, we needed to dig deep and understand:",
          "Which platforms were performing best in terms of sales, traffic, and conversion rates?",
          "Which categories and products were thriving on each platform?",
          "Which products were slow-moving on certain platforms but doing well on others?",
          "We didn’t just want to expand blindly; we wanted to strategically position iSiSOrganic where it had the highest potential to win. We discovered that some products weren’t moving fast due to poor catalog structure and low visibility, rather than a lack of demand. This audit gave us total clarity on where to optimize, where to scale, and where to shift our focus.",
          "Before scaling iSiSOrganic’s presence across Noon, Breadfast, Goodsmart, we needed to dig deep and understand:",
          "Which platforms were performing best in terms of sales, traffic, and conversion rates?",
          "Which categories and products were thriving on each platform?",
          "Which products were slow-moving on certain platforms but doing well on others?",
          "We didn’t just want to expand blindly, we wanted to strategically position iSiSOrganic where it had the highest potential to win, Some products weren’t moving fast due to poor catalog structure and visibility rather than lack of demand. This audit gave us clarity on where to optimize, where to scale, and where to shift focus.",
          "Before scaling iSiSOrganic’s presence across Noon, Breadfast, Goodsmart, we needed to dig deep and understand:",
          "Which platforms were performing best in terms of sales, traffic, and conversion rates?",
          "Which categories and products were thriving on each platform?",
          "We didn’t just want to expand blindly, we wanted to strategically position iSiSOrganic where it had the highest potential to win, Some products weren’t moving fast due to poor catalog structure and visibility rather than lack of demand. This audit gave us clarity on where to optimize, where to scale, and where to shift focus.",
          "After identifying the strengths and weaknesses across platforms, we went all in on optimizing iSiSOrganic's catalog to dominate in every marketplace.",
          "🚀 What We Improved:",
          "Expanded catalog presence across all platforms. Every product that had demand was properly listed, optimized, and promoted.",
          "Refined slow-moving products by adjusting descriptions, pricing, and ad strategies to improve visibility and conversions.",
          "Aligned stock availability across platforms to ensure that products didn’t lose momentum due to fulfillment issues.",
          "Digitized top offline sellers by listing retail-winning products that were previously completely missing from e-commerce platforms.",
          "By customizing our approach for each platform, we weren’t just listing iSiSOrganic products—we were positioning them to sell.",
          "After identifying the strengths and weaknesses across platforms, we went all in on optimizing iSiSOrganic catalog to dominate in every marketplace.",
          "🚀 What We Improved:",
          "∙Expanded iSiSOrganic catalog presence across all platforms, every product that had demand was properly listed, optimized, and promoted.",
          "∙Refined Slow moving products by adjusting descriptions, pricing, and ad strategy to improve visibility and conversions.",
          "∙Aligned stock availability across platforms to ensure that products didn’t get lost due to fulfillment issues.",
          "∙Some offline retail-winner products were not even listed on e commerce platforms",
          "By customizing our approach for each platform, we weren’t just listing iSiSOrganic products, we were positioning them to sell.",
          "After identifying the strengths and weaknesses across platforms, we went all in on optimizing iSiSOrganic catalog to dominate in every marketplace.",
          "∙Refined Slow moving products by adjusting descriptions, pricing, and ad strategy to improve visibility and conversions.",
          "∙Aligned stock availability across platforms to ensure that products didn’t get lost due to fulfillment issues.",
          "∙Some offline retail-winner products were not even listed on e commerce platforms",
          "By customizing our approach for each platform, we weren’t just listing iSiSOrganic products, we were positioning them to sell.",
          "E-commerce isn’t just about having great products—it’s about knowing when and how to sell them.",
          "Once we had the catalog in place, we built a promotional plan tailored to the seasonality of the Egyptian market. This ensured iSiSOrganic maintained a constant, highly visible presence during peak shopping periods, backed by a consistent message across its entire e-commerce ecosystem.",
          "By aligning seasonal trends with consumer behavior, we ensured that iSiSOrganic wasn’t just running promotions for the sake of it. Every discount had a purpose, a strategy, and a direct impact on the bottom line.",
          "E-commerce isn’t just about having great products, it’s about knowing when and how to sell them.",
          "Once we had the catalog in place, we built a promotions plan tailored to the seasonality of the Egyptian market, ensuring iSiSOrganic had a constant presence during peak shopping periods, with consistent message across the entire iSiSOrganic e commerce presence.",
          "By aligning seasonal trends with consumer behavior, we ensured that iSiSOrganic wasn’t just running promotions for the sake of it, every discount had a purpose, a strategy, and a direct impact on sales.",
          "E-commerce isn’t just about having great products, it’s about knowing when and how to",
          "sell them. Once we had the catalog in place, we built a promotions plan tailored to the seasonality of the Egyptian market, ensuring iSiSOrganic had a constant presence during",
          "peak shopping periods, with consistent message across the entire iSiSOrganic e commerce presence. By aligning seasonal trends with consumer behavior, we ensured that iSiSOrganic wasn’t just running promotions for the sake of it, every discounthad a purpose, a strategy, and a direct impact on sales.",
          "Scaling fast can be a double-edged sword. If you don’t plan ahead, you end up with stock shortages, fulfillment failures, and lost sales opportunities. That’s why we worked closely with iSiSOrganic to forecast product demand, adjust production timelines, and optimize fulfillment.",
          "Forecasted demand per product category to ensure the right SKUs were produced in bulk ahead of time.",
          "Boosted fulfillment rates to reach 80%, ensuring iSiSOrganic had the stock to support its rapid growth.",
          "No last-minute rush. No lost sales. Just a seamless execution plan to scale without breaking.",
          "Scaling fast can be a double edged sword. If you don’t plan ahead, you end up with stock shortages, fulfillment failures, and lost sales opportunities.That’s why we worked closely with iSiSOrganic to forecast product demand, adjust production timelines, and optimize fulfillment.",
          "Forecasted demand per product category to ensure the right SKUs were produced in bulk ahead of time. Boosted fulfillment rates",
          "to reach 80%, ensuring iSiSOrganic had the stock to support its growth.",
          "No last minute rush. No lost sales. Just a seamless execution plan to scale without breaking.",
          "Forecasted demand per product category to ensure the right SKUs were produced in bulk ahead of time. Boosted fulfillment rates to reach 80%, ensuring iSiSOrganic had the stock to its growth. No last minute rush. No lost sales. Just a seamless execution plan to scale",
          "without breaking.",
          "With the strategy locked in, we built a clear forecast for the months ahead, tracking spending, sales growth, and advertising efficiency.",
          "Key Metrics We Focused On:",
          "Sales growth projections per platform based on historical data.",
          "Advertising spend vs. return (CIR) to maintain profitability while scaling.",
          "Conversion rate trends to identify and fix underperforming areas in real time.",
          "This wasn’t about guesswork—it was about data-backed decisions that set iSiSOrganic up for long-term success.",
          "With the strategy locked in, we built a clear forecast for the months ahead, tracking spending, sales growth, and advertising efficiency.",
          "Key Metrics We Focused On:​Sales growth projections per platform based on historical data.​Advertising spend vs. return (CIR) to maintain profitability while scaling.​Conversion rate trends to identify and fix underperforming areas in real time.",
          "This wasn’t about guesswork, it was about data-backed decisions that set iSiSOrganic up for long-term success.",
          "Key Metrics We Focused On:​Sales growth projections per platform based on historical data.​Advertising spend vs. return (CIR) to maintain profitability while scaling.​Conversion rate trends to identify and fix underperforming areas in real time.",
          "This wasn’t about guesswork, it was about data-backed decisions that set iSiSOrganic up for long-term success.",
          "Since we began our Amazon journey earlier than the other platforms, scaling and implementing our overarching strategy was a seamless process.",
          "Launching the Brand Store We built a dedicated Amazon Brand Store to effectively communicate iSiSOrganic's core message. This strategic hub was designed to cross-sell products, increase basket size, and boost the average order value (AOV)—ultimately keeping the Cost to Income Ratio (CIR) highly efficient.",
          "Call to Action / Highlight Box Refer to our case study—iSiSOrganic Rocking 900% Growth in 4 Months—to get a behind-the-scenes glimpse of our initial Amazon launch strategy.",
          "Since we already started our Amazon Journey earlier than all other platforms, it was easier to scale and implement the strategy that we talked about in the previous section. Refer to iSiSOrganic rocking 900% growth in 4 months to get a behind the scenes glimpse of our Amazon Launch strategy with iSiSOrganic.",
          "Utilize Brand Store:",
          "A brand store was launched on Amazon with the purpose of communicating the brand message, and increasing basket size, hence increasing average order value, keeping CIR to a satisfying level",
          "Since we already started our Amazon Journey earlier than all other platforms, it was easier to scale and implement the strategy that we talked about in the previous section. Refer to iSiOrganic rocking 900% growth in 4 months to get a behind the scenes glimpse of our Amazon Launch strategy with iSiSOrganic.",
          "A brand store was launched on Amazon with the purpose of communicating the brand message, and increasing basket size, hence increasing average order value, keeping CIR to a satisfyinglevel.",
          "We executed a highly tailored advertising plan, formulated strictly around the forecasted spend and sales projections established during our initial planning phase.",
          "How We Leveraged Ad Formats:",
          "Sponsored Brands: Used to effectively communicate the brand's core message, increase top-of-mind awareness, and drive sales.",
          "Sponsored Products: Deployed strategically to capture high-intent search traffic and maximize direct sales.",
          "Sponsored Display: Utilized to drive conversions, build broader awareness, and create a defensive moat for brand protection against competitors.",
          "Executed a tailored advertising plan which was formulated based on the forecasted spend and sales that were discussed in the first section “Planning” .Leverage Sponsored Brands for Brand message communication, sales, and awareness. Leverage Sponsored Products for Sales. Leverage Sponsored Display for Sales, awareness, and brand protection.",
          "Noon offers a brand store with an annual subscription fee, however there we can always utilize sponsored brands to communicate brand message, as well as sponsored products to drive sales.",
          "The Other E-commerce Platforms:",
          "Based on historical data and dblshot's internal analysis, we discovered that specific product categories had massive potential on GoodsMart but were currently underperforming.",
          "The Action Plan:",
          "Targeted Category Promotions: To capture this untapped demand, we launched strategic promotional campaigns designed to boost visibility, shift slow-moving inventory, and drive immediate sales on the platform.",
          "The Other E commerce platforms:",
          "Based on the Historical data, and Dblshot Analysis we discovered that some categories have potential on Goodsmart yet performing relatively low. ∙A category promotion was launched to push sale on GoodsMart.",
          "Based on the Historical data, and Dblshot Analysis we discovered that some categories have potential on Goodsmart yet performing relatively low. A category promotion was launched to push sale on GoodsMart.",
          "To capture attention and drive immediate conversions on Breadfast, we strategically deployed a Hero Banner. This high-visibility placement was designed to push sales for specific, high-priority products and categories.",
          "Internationalization: A Step Towards Global E-commerce Excellence",
          "A Hero Banner was executed strategically to drive sales on selected products and categories",
          "Internationalization:",
          "A step towards Global E commerce Excellence:",
          "A Hero Banner was executed strategically to drive sales on selected products and categories.",
          "Late 2024, we concluded all the backend operational necessities to launch iSiSOrganic in Amazon KSA. Product listing and catalog photoshoot are now concluded and ready for promotions. A Brand Store was created in Amazon KSA with the same messaging and Tone of voice with respect to the cultural difference and guidelines.",
          "Home Page Banner on Rabbit platform to maximize sales, and awareness during Ramadan.",
          "A Year of Record Breaking Growth After implementing a platform specific strategy, promotional planning, and operational enhancements, iSiSOrganic witnessed unprecedented growth across all e-commerce platforms.",
          "A Year of Record Breaking Growth After implementing a platform specific strategy, promotional planning, and operationalenhancements, iSiSOrganic witnessed unprecedented growth across all ecommerce",
          "Total E-commerce",
          "Amazon Sales Growth",
          "Breadfast sales growth",
          "noon sales growth",
          "Goodsmart sales growth",
          "Total E-commerce Growth YOY",
          "Beyond the numbers, the transformation was about turning iSiSOrganic from an underperforming e-commerce player into a dominant force in FMCG ecommerce sales.",
          "Beyond the numbers, the transformation was about turning iSiSOrganic from an underperforming ecommerce player into a dominant force in FMCG ecommerce sales.",
          "Beyond the numbers, the transformation was about turning iSiSOrganic from an underperforming e-commerce player into a dominant force in FMCG e-commerce sales."
        ]
      }
    ]
  } as const;
